name: OpenAPI JSON:API
description: OpenAPI support for the JSON:API module.
type: module
package: Web Services
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - openapi:openapi
  - schemata:schemata
  - schemata:schemata_json_schema

# Information added by Drupal.org packaging script on 2021-09-19
version: '3.0.2'
project: 'openapi_jsonapi'
datestamp: 1632062732
