name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2021-12-09
version: '9.3.0'
project: 'drupal'
datestamp: 1639051328
