name: OpenAPI
type: module
description: Connects Drupal to the OpenAPI Javascript Library
core: 8.x
core_version_requirement: '^8 || ^9'
package: OpenAPI
dependencies:
  - drupal:serialization

# Information added by Drupal.org packaging script on 2021-09-26
version: '8.x-2.0'
project: 'openapi'
datestamp: 1632637191
